### ISSUE TITLE
Using singleuser.extraAnnotations results in persistent keyError

### ISSUE THREAD

**Issue by ghost** [jupyterhub/kubespawner#340] opened 2019-07-25 19:41 UTC
Context: In order to monitor the resources of singleuser notebooks from Datadog.. an annotation needs to be created on all instances that are spun up in Kubernetes.

The following code is passed to the KubeSpawner to do this

```yaml
singleuser:
  image:
    name: ${singleuser_patched_repository}
    tag: "${singleuser_patched_version}"
    imagePullPolicy: IfNotPresent
  startTimeout: 120
  cloudMetadata:
    enabled: true
  extraTolerations:
    - key: ${notebook_eks_worker_taint_key}
      operator: Equal
      value: ${notebook_eks_worker_taint_value}
      effect: NoSchedule

  extraNodeAffinity:
    required:
      - matchExpressions:
        - key: ${notebook_eks_worker_taint_key}
          operator: In
          values:
            - ${notebook_eks_worker_taint_value}

  extraAnnotations:
    ad.datadoghq.com/tags: '{"jupyter_notebook_instance":"demo03"}'
```

**When this code is passed to Jupyter, the notebook will fail to start with a 500 Error and the following logs**

```
[E 2019-07-25 15:44:43.719 JupyterHub user:477] Unhandled error starting admin's server: '"jupyter_notebook_instance"'
[E 2019-07-25 15:44:44.150 JupyterHub web:1788] Uncaught exception GET /hub/user/admin/ (10.0.2.167)
    HTTPServerRequest(protocol='http', host='jupyter.demo03.qa.abacusinsights.io', method='GET', uri='/hub/user/admin/', version='HTTP/1.1', remote_ip='10.0.2.167')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 1062, in get
        await self.spawn_single_user(user)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 715, in spawn_single_user
        timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 636, in finish_user_spawn
        await spawn_future
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 489, in spawn
        raise e
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 409, in spawn
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/usr/local/lib/python3.6/dist-packages/kubespawner/spawner.py", line 1683, in _start
        pod = yield self.get_pod_manifest()
      File "/usr/local/lib/python3.6/dist-packages/kubespawner/spawner.py", line 1314, in get_pod_manifest
        annotations = self._build_common_annotations(self._expand_all(self.extra_annotations))
      File "/usr/local/lib/python3.6/dist-packages/kubespawner/spawner.py", line 1251, in _expand_all
        return {k: self._expand_all(v) for k, v in src.items()}
      File "/usr/local/lib/python3.6/dist-packages/kubespawner/spawner.py", line 1251, in <dictcomp>
        return {k: self._expand_all(v) for k, v in src.items()}
      File "/usr/local/lib/python3.6/dist-packages/kubespawner/spawner.py", line 1253, in _expand_all
        return self._expand_user_properties(src)
      File "/usr/local/lib/python3.6/dist-packages/kubespawner/spawner.py", line 1244, in _expand_user_properties
        unescaped_servername=servername
    **KeyError: '"jupyter_notebook_instance"'**
```

When the extraAnnotation is removed, the notebook will start as expected.

**Comment by sethatron** [comment] 2019-07-28 16:20
I submitted this on an older account. Using this now. Please @ me for further information

**Comment by consideRatio** [comment] 2020-10-25 16:13
Ah, this is a duplicate of #316 which I have suggested a concrete action plan for and I welcome anyone to submit a PR for.

**Closed by consideRatio** 2020-10-25 16:13 UTC
