### ISSUE TITLE
AKS reliability issue - pending spawn / pending stop - resolved but undocumented fix

### ISSUE THREAD

**Issue by tjcrone** [jupyterhub/kubespawner#282] opened 2018-12-01 14:41 UTC
I am having intermittent problems with the KubeSpawner on Azure, where the hub thinks that a user server is either pending start or pending stop, but the pod on the cluster for that user is not being started or not being stopped. This is an intermittent problem that seems to come and go. The only way I have found of straightening things out (temporarily) is to delete the hub pod so that it automatically restarts. 

Here is a section of the hub logs which may be relevant:
```
[I 2018-12-01 14:26:23.386 JupyterHub proxy:301] Checking routes
[I 2018-12-01 14:27:15.255 JupyterHub log:158] 200 GET /hub/admin (tjcrone@10.240.0.13) 35.11ms
[I 2018-12-01 14:27:18.274 JupyterHub proxy:264] Removing user tjcrone from proxy (/user/tjcrone/)
[I 2018-12-01 14:27:18.277 JupyterHub spawner:1770] Deleting pod jupyter-tjcrone
[E 2018-12-01 14:27:21.402 JupyterHub gen:974] Exception in Future <Future finished exception=ReadTimeoutError("HTTPSConnectionPool(host='nlsees-201-neanderthallab-17dca6-28535aba.hcp.centralus.azmk8s.io', port=443): Read timed out. (read timeout=None)",)> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 970, in error_callback
        future.result()
      File "/usr/local/lib/python3.6/dist-packages/kubespawner/spawner.py", line 1667, in _start
        body=pvc
      File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/usr/local/lib/python3.6/dist-packages/kubespawner/spawner.py", line 1489, in asynchronize
        return method(*args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/apis/core_v1_api.py", line 5950, in create_namespaced_persistent_volume_claim
        (data) = self.create_namespaced_persistent_volume_claim_with_http_info(namespace, body, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/apis/core_v1_api.py", line 6035, in create_namespaced_persistent_volume_claim_with_http_info
        collection_formats=collection_formats)
      File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 321, in call_api
        _return_http_data_only, collection_formats, _preload_content, _request_timeout)
      File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 155, in __call_api
        _request_timeout=_request_timeout)
      File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 364, in request
        body=body)
      File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/rest.py", line 266, in POST
        body=body)
      File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/rest.py", line 166, in request
        headers=headers)
      File "/usr/local/lib/python3.6/dist-packages/urllib3/request.py", line 72, in request
        **urlopen_kw)
      File "/usr/local/lib/python3.6/dist-packages/urllib3/request.py", line 150, in request_encode_body
        return self.urlopen(method, url, **extra_kw)
      File "/usr/local/lib/python3.6/dist-packages/urllib3/poolmanager.py", line 322, in urlopen
        response = conn.urlopen(method, u.request_uri, **kw)
      File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
        _stacktrace=sys.exc_info()[2])
      File "/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py", line 367, in increment
        raise six.reraise(type(error), error, _stacktrace)
      File "/usr/local/lib/python3.6/dist-packages/urllib3/packages/six.py", line 686, in reraise
        raise value
      File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
        chunked=chunked)
      File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 386, in _make_request
        self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
      File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 317, in _raise_timeout
        raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
    urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nlsees-201-neanderthallab-17dca6-28535aba.hcp.centralus.azmk8s.io', port=443): Read timed out. (read timeout=None)
    
[I 2018-12-01 14:27:23.340 JupyterHub proxy:301] Checking routes
[I 2018-12-01 14:27:23.540 JupyterHub log:158] 200 GET /hub/api/users (cull-idle@127.0.0.1) 50.42ms
[W 181201 14:27:23 cull_idle_servers:128] Not culling server tjcrone with pending stop
[W 2018-12-01 14:27:28.277 JupyterHub base:786] User tjcrone: server is slow to stop
```
At this stage, the hub thinks the server is pending stop, but the server pod is up and running and it is not being stopped. Something similar can happen when the hub tries to start a pod, but no pod launches, but the hub continues to think that a server is pending start.

Any idea what is going on? Suggestions on better troubleshooting?

**Comment by minrk** [comment] 2018-12-04 10:44
Thanks @willingc! @yuvipanda any insight into what might cause periodic network timeouts on azure?

**Comment by tjcrone** [comment] 2018-12-04 15:31
Thanks @minrk. So you think this could be a network timeout issue? We never used to have problems like this, then they started one day a few weeks back. It is possible that Azure changed something. I upgraded to v0.8-676f4f3, and continue to see the problem.

@willingc, in terms of reproducibility, if we wait long enough, the hub will reliably get confused. I am not able to create confusion on demand yet. If you or anyone else has any suggestions on how to collect additional information, please let me know. It would be great to be able to solve this.

**Comment by sgulseth** [comment] 2019-01-25 13:47
Just setup Jupyterhub on AKS and ran into this issue. When debugging it I noticed that the first attempt to start/stop servers always succeeded. Starting a hub and then waiting usually ended up with the next action failing because of an eventual timeout. Looking more into it, with some unsophisticated timing involved, it was usually around 4 minutes it took for the next action to fail. This corresponds to the Azure Load Balancer default keep alive ttl.

Every pod in k8s should get the Kubernetes api host injected as an environment variable, this is then used by the SDKs to load in-cluster config(see https://github.com/kubernetes-client/python-base/blob/master/config/incluster_config.py#L23-L24). On AKS this is for some reason the public api dns, `xxx.hcp.centralus.azmk8s.io`.

```json
» ksysdpo tunnelfront-5774f86cb5-fffwc | grep KUBERNETES_SERVICE_HOST
      KUBERNETES_SERVICE_HOST:       some-address.hcp.westeurope.azmk8s.io
```

K8s also exposes the api by default on an internally routed host, `kubernetes.default.svc.cluster.local`. However for some reason when I tried to manually set the env var in the pod AKS would just convert it to the public one when the pod was deployed. 

In an attempt to verify my suspicions that it was the ALB keep alive that was at fault I wrapped the hub-image and manually hard coded the env var `KUBERNETES_SERVICE_HOST` to the locally routed one:

```Dockerfile
» cat Dockerfile
FROM jupyterhub/k8s-hub:0.7.0

ENV PATH="/srv/bin:${PATH}"

COPY jupyterhub.sh /srv/bin/jupyterhub

» cat jupyterhub.sh
#!/bin/bash

export KUBERNETES_SERVICE_HOST="kubernetes.default.svc.cluster.local"

/usr/local/bin/jupyterhub $@
``` 

With this image built, pushed and Jupyterhub using it I no longer see any timeouts. The image is available at `sgulseth/jupyter-k8s-hub:0.7.0` if you wanna test it out.

---

I'm not sure if this is unexpected behaviour from the SDK or Azure Load balancer, but for my sake I only need Jupyterhub running over the weekend, so I'm OK with a temp ugly hack.

**Comment by consideRatio** [comment] 2020-10-25 14:22
@sgulseth @yuvipanda @ryanlovett do you know if AKS still does this and this is still relevnt? If so, perhaps we should document it in the Z2JH guide for example under the AKS section?

**Comment by ryanlovett** [comment] 2020-10-25 15:08
@consideRatio Not sure. Our hubs are no longer running on Azure.

**Comment by yuvipanda** [comment] 2020-10-26 06:41
Documenting it is probably not a bad idea! Azure definitely needs a lot of hand-holding to work well, and the more support we can give folks the better.

**Comment by tjcrone** [comment] 2020-10-26 11:32
I can confirm that this continues to happen on our AKS deployments. This morning I tried starting a notebook server and got the ```Your server is starting up.``` page, but there is no action at all and the only event is ```Server requested``` Meanwhile, the hub posts this in its logs:
```
[I 2020-10-26 11:16:55.210 JupyterHub log:174] 302 GET / -> /hub/ (@10.0.129.138) 1.44ms
[I 2020-10-26 11:16:55.509 JupyterHub log:174] 302 GET /hub/ -> /hub/spawn (tjcrone@10.0.129.138) 17.29ms
[I 2020-10-26 11:16:55.557 JupyterHub log:174] 200 GET /hub/spawn (tjcrone@10.0.129.138) 16.04ms
[W 2020-10-26 11:17:00.256 JupyterHub base:950] User tjcrone is slow to start (timeout=0)
[I 2020-10-26 11:17:00.261 JupyterHub log:174] 302 POST /hub/spawn -> /hub/spawn-pending/tjcrone (tjcrone@10.0.129.138) 60.71ms
[I 2020-10-26 11:17:00.293 JupyterHub pages:347] tjcrone is pending spawn
[I 2020-10-26 11:17:00.294 JupyterHub log:174] 200 GET /hub/spawn-pending/tjcrone (tjcrone@10.0.129.138) 2.49ms
[I 2020-10-26 11:17:04.725 JupyterHub log:174] 200 GET /hub/health (@10.0.128.199) 0.77ms
```
On shutdown, basically the same thing happens in reverse. The hub reports that the user is "slow to stop", which means that it will not stop at all until the idle timeout.

To solve this I will do a rollback with ```--recreate-pods``` so the hub pod restarts and it will be fine for a while. I do not know how to determine the kubespawner version or get logs from the kubespawner. If anyone else has any suggestions on how to collect additional information, please let me know. It would be great to be able to solve this.

**Comment by tjcrone** [comment] 2020-10-26 11:36
Our configuration files can be found here: https://github.com/pangeo-data/pangeo-cloud-federation/tree/staging/deployments/ooi.

**Comment by consideRatio** [comment] 2020-10-26 12:00
@tjcrone okay so there is still an issue with slow pending spawn and pending stop.
- What version of the KubeSpawner is used?
  - [DaskHub 4.4.2 is used](https://github.com/pangeo-data/pangeo-cloud-federation/blob/ccd30c420d8b6a50eca8193ef3cdd25bdb0c1342/pangeo-deploy/Chart.yaml#L7-L12) -> [Z2JH 0.9.1 is used](https://github.com/dask/helm-chart/blob/9e809c8336aeed33feb7dbf452fd8c8ca9c16fbe/daskhub/Chart.yaml#L8-L13) -> [KubeSpawner 0.11.1 is used](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/0.9.1/images/hub/requirements.txt#L31) but 0.14.1 is available and https://github.com/jupyterhub/kubespawner/pull/433 has been merged since.
- Did you apply the suggestion in https://github.com/jupyterhub/kubespawner/issues/282#issuecomment-457577684? Did it help doing that?

**Comment by tjcrone** [comment] 2020-10-26 13:04
I would be happy to wrap the hub image as suggested in https://github.com/jupyterhub/kubespawner/issues/282#issuecomment-457577684, but it is not clear to me where in my set of charts I would specify an override on this image. @consideRatio would you be willing to provide guidance on where this would go? I'm guessing it would go [here](https://github.com/pangeo-data/pangeo-cloud-federation/blob/staging/deployments/ooi/config/common.yaml), but I'm not sure and I do not know how to specify the hub image in this chart. Thanks!

**Comment by tjcrone** [comment] 2020-10-26 13:26
My guess is that this workaround will work, because my pods also have the public address set for KUBERNETES_SERVICE_HOST. It's not clear to me though why the load balancer would timeout and prevent access through this route, or why this is not a serious problem for everyone using AKS. I wonder if there is a way that we can disable the timeout, set it to some very long time, or force AKS to use the local route for KUBERNETES_SERVICE_HOST. Is this something that I should bring to Azure support? Or can we control the load balancer in finer detail when we create it?

**Comment by consideRatio** [comment] 2020-10-26 13:42
@tjcrone you can apply it [here](https://github.com/pangeo-data/pangeo-cloud-federation/blob/staging/deployments/ooi/config/common.yaml) like you say, and you would do it by simplest by something like this.

```yaml
# nest this under daskhub -> jupyterhub, so extraEnv comes next to extraConfig etc
hub:
  extraEnv:
    KUBERNETES_SERVICE_HOST: kubernetes.default.svc.cluster.local
```

---

**Comment by consideRatio** [comment] 2020-10-26 13:45
It would be relevant to get confirmation that the extraEnv was helpful by itself, so if you can validate it is relevant to have separately from it being relevant to have both the latest KubeSpawner it would be relevant to know.

**Comment by tjcrone** [comment] 2020-10-26 13:48
Okay sounds good. Adding an environment variable to the chart seems much more reasonable than building a new hub image. I will try the ```KUBERNETES_SERVICE_HOST``` fix first and let you know what I find. Thank you!

**Comment by tjcrone** [comment] 2020-10-26 15:33
Okay, the good news is that I can reliably reproduce this issue by waiting approximately 4 minutes after any network activity (the default timeout for the load balancer). The load balancer timeout can be [increased](https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-tcp-idle-timeout) to 30 min maximum, but that isn't really enough to help here.

The bad news is that setting `KUBERNETES_SERVICE_HOST` to `kubernetes.default.svc.cluster.local` on the hub pod did not seem to help. I'm wondering if perhaps this is needed on other pods as well? Or maybe there is a DNS issue so that if I set it to an internal IP address it might work? Inside the hub pod `kubernetes.default.svc.cluster.local` resolves to 10.1.0.1, which is not on the same subnet as the pods in the cluster, which are on 10.0.x.x.. Not sure if there is another subnet that everything talks on or if this could be a problem.

Anyway, I am able to reproduce, and I would be more than happy to work through this if you would like to try. I would greatly appreciate it! Thanks.

**Comment by consideRatio** [comment] 2020-10-26 15:34
@tjcrone thanks for this feedback! What if you use the 0.10.0-beta.1 image?

**Comment by yuvipanda** [comment] 2020-10-27 06:01
@tjcrone fwiw, after I deployed https://github.com/jupyterhub/kubespawner/pull/433 the exact same problem you are describing went away.

**Comment by tjcrone** [comment] 2020-10-27 09:12
Okay time for a report. After switching to 0.10.0-beta.1, I have been unable to reproduce any of the various spawner issues that have been causing us problems on AKS since this issue was opened. Fantastic! Well done! I have not removed the  `KUBERNETES_SERVICE_HOST` environment variable and I am inclined to just keep it. If you would like me to try things without it I can do that, but if not I suggest we just close for the win.

**Comment by consideRatio** [comment] 2020-10-27 09:21
@tjcrone if possible, it would be great to know if it is a needed step or not. It may come back and haunt us for deviating from the defaults, so if it is to be done, having confirmed its value would be great.

Im looking to translate these insights into documentation updates in the z2jh.jupyter.org guide

**Comment by tjcrone** [comment] 2020-11-03 17:02
Okay after about a week of testing, without using a `KUBERNETES_SERVICE_HOST` environment variable, we have not seen this issue crop up. Looks like the newest version of the kubespawner is working well with the latest versions of kubernetes on AKS. I think this can be closed when you are ready @consideRatio. Thank you everyone for the input and help!

**Comment by consideRatio** [comment] 2020-11-03 17:04
Thanks for the followup @tjcrone and your help to investigate this! :tada:

**Closed by consideRatio** 2020-11-03 17:04 UTC

**Comment by meeseeksmachine** [comment] 2021-03-21 20:28
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/jupyterhub-on-k8s-azure-intermittently-times-out-with-no-events/8444/2

**Comment by meeseeksmachine** [comment] 2021-03-21 22:56
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/jupyterhub-on-k8s-azure-intermittently-times-out-with-no-events/8444/3
