### ISSUE TITLE
c.KubeSpawner.environment not interpreting callables

### ISSUE THREAD

**Issue by Khagesh16** [jupyterhub/kubespawner#824] opened 2024-03-06 16:48 UTC
### Bug description
This change is causing an issue when the environment accepts the callable function. https://github.com/jupyterhub/kubespawner/pull/759

This same piece of logic used to be working on version 5.0.0 but failing on the latest version.

### How to reproduce
This is a sample dictionary which we are passing to ```c.KubeSpawner.environment ``` with other environment variables.

```
{
    "JUPYTERHUB_SINGLEUSER_APP": "jupyter_server.serverapp.ServerApp",
    "USERNAME": lambda spawner: str(spawner.user.name),
    "JUPYTER_ENABLE_LAB": "yes",
    "AWS_STS_REGIONAL_ENDPOINTS": "regional",
}
```

#### Expected behaviour
It should replace the username with actual username

```
{
    "CPU_LIMIT": "3.0",
    "CPU_GUARANTEE": "2.0",
    "JUPYTERHUB_SINGLEUSER_APP": "jupyter_server.serverapp.ServerApp",
    "USERNAME": "kpandya",
    "JUPYTER_ENABLE_LAB": "yes"}
```

#### Actual behaviour

```
{"CPU_LIMIT": "3.0",
    "CPU_GUARANTEE": "2.0",
    "JUPYTERHUB_DEFAULT_URL": "/lab",
    "JUPYTERHUB_SINGLEUSER_APP": "jupyter_server.serverapp.ServerApp",
    "USERNAME": < function < lambda > at 0x7ff12b035120 > ,
    "JUPYTER_ENABLE_LAB": "yes"}
```

### Your personal set up

 - OS:
 
 - Version(s):
 

<details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

<details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

<details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>

**Comment by jabbera** [comment] 2024-03-26 13:48
This is a dupe of https://github.com/jupyterhub/kubespawner/issues/815

**Closed** 2024-03-28 08:48 UTC
Labels: bug
