### ISSUE TITLE
Jupyterhub: supporting multiple service accounts & namespaces with a single server instance

### ISSUE THREAD

**Issue by foxish** [jupyterhub/kubespawner#79] opened 2017-08-29 20:46 UTC
The readme says:

> Spawn multiple hubs in the same kubernetes cluster, with support for namespaces. You can limit the amount of resources each namespace can use, effectively limiting the amount of resources a single JupyterHub (and its users) can use. This allows organizations to easily maintain multiple JupyterHubs with just one kubernetes cluster, allowing for easy maintenance & high resource utilization.

In another model, where there is a single hub, we may have individual user pods (notebook instances) are created in different namespaces using different service accounts (on behalf of a user), where the association between JupyterHub identity and pod service-account is maintained separately in a configmap.
Has something like this been explored before? Are you aware of limitations if one were to try and do this?

This would be related to https://github.com/jupyterhub/kubespawner/issues/76 and https://github.com/jupyterhub/kubespawner/issues/75

cc @yuvipanda

**Comment by foxish** [comment] 2017-08-30 12:39
The broad goal is to have: a multi-tenant JupyterHub capable of launching pods on behalf of a user, with a particular service account into **any** existing namespace.  
Based on some of the conversation we had on gitter and adding some more thoughts.

More concretely, we could achieve the above with the following (hypothetically).
1. Kubespawner adds a mechanism to read from a ConfigMap, and applies a service account identity to a pod, based on the OAuth identity. This ConfigMap would contain associations between JupyterHub user/group and Service Accounts.
2. UI provides a list of namespaces to choose from, into which a user can launch their notebook-pod (not sure how this can be plumbed through). 
3. If user X cannot launch their pod in namespace Y that they chose, it would surface that error back up to the UI in some way.

**Comment by erolosty** [comment] 2017-09-18 13:21
What would work best for me (and I suspect many others) would be if the function that defines namepspace resuses the templating supported for pod_name and pvc eg:

c.KubeSpawner.pod_name_template = '{username}-jupyter'   #already supported
c.KubeSpawner.namespace = '{username}-spark-cluster'       #would be great

**Comment by yuvipanda** [comment] 2017-09-21 23:51
@foxish @erolosty with https://github.com/jupyterhub/kubespawner/pull/84 we can now launch singleuser pods with access to the namespace' default service account.

**Comment by yuvipanda** [comment] 2017-09-21 23:52
@erolosty with namespace_template, would we also be creating the namespace if it doesn't exist? If we create them, do we also clean up?

**Comment by foxish** [comment] 2017-09-21 23:56
@yuvipanda, thank you! I think that's a good step ahead.

**Comment by erolosty** [comment] 2017-09-25 13:13
@yuvipanda Hadn't considered it. The behavior that makes most sense for me would be yes to both create and destroy unconditionally, but I can absolutely see how this could be a surprise and an issue for many.

What do you think about using:
  c.KubeSpawner.namespace**_template** 

implies the creation of the namespace, but the deletion would need to be opt-in eg

c.KubeSpawner.namespace_template_cleanup = true

**Comment by yuvipanda** [comment] 2017-09-29 23:49
@erolosty that makes sense to me. We already do something like that for PVCs, so we can extend that for templates.

**Comment by yuvipanda** [comment] 2017-09-29 23:51
Also I'm taking steps towards having RBAC on by default. https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/209 sets it up in our default helm chart.

**Comment by consideRatio** [comment] 2020-10-25 02:24
Closing this as a duplicate of #76.

**Closed by consideRatio** 2020-10-25 02:24 UTC
