### ISSUE TITLE
Per user environment variables on spawning pods

### ISSUE THREAD

**Issue by cmrfrd** [jupyterhub/kubespawner#267] opened 2018-09-29 22:14 UTC
Is it possible to control per user environment variables for user pods from the `c.KubeSpawner.environment` attribute?

The [docs](https://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html) say for the `c.KubeSpawner.environment` attribute that "the value can be a string or a <b>callable</b>" and that "If it is a callable, it will be called with one parameter (the spawner instance)" 

Is it possible to extract the `{username}` or `{userid}` of the current user from the spawner instance in said callable and have that callable hit some database or something to receive unique per user values to be then set as environment variables ?

Some applications of this idea can be
1. Adding a GITHUB_TOKEN environment variable for the user so they can push to github repositories
2. Per login TOKEN environment variables created on startup of a users pod
...

**Comment by BerserkerTroll** [comment] 2018-10-23 23:15
`Spawner` has `user` field, which contains user's name: https://github.com/jupyterhub/jupyterhub/blob/65d9ac3c619a6296a703e6fe3f20d9af7cb45dc3/jupyterhub/spawner.py#L121
So in the code below
```python
c.KubeSpawner.environment = {
   'USERNAEM' : lambda spawner: str(spawner.user.name),
}
```
`USERNAEM` envvar will be equal to user's name (`str` could be unnecessary here) in the container.

But it could be easier to derive from `KubeSpawner` and override the `get_env` method. It is advised in the `Spawner`: https://github.com/jupyterhub/jupyterhub/blob/2d94b2999f9db8b72a981cc0abc16dfcc6071ba4/jupyterhub/spawner.py#L348 Lambda is limited to one expression.

BTW, `Spawner` instance has the field `authenticator`, which surprisingly refers to the authenticator. The authenticator could be used to map usernames to some additional information (i.e. query LDAP server for uid or home dir). The problem is that `get_env` is not a coroutine and it is dangerous to perform potentially long running operations there.
The kludge I invented: I've derive from `LDAPAuthenticator` and added a blocking method to query additional user info from LDAP server. The trick is that the blocking method is decorated with `@func.ttl_cache()` decorator from `cachetools`. Then I also override the `authenticate` method, which is fortunately a coroutine, where I schedule the blocking method to a thread pool thus calling it "asynchronously". And the result of the call is cached so that when I call the method from `get_env`, I don't have to query the LDAP server, if the cache is not expired yet.
You may override `add_user` instead of `authenticate`. `add_user` also could be a coroutine and it is called when a user is added to the hub. This could happen not only when a user authenticates, but also when a user added by an admin or when the Hub is restarted and re-populate users from DB. You may also make the cache permanent so it won't expire.

But really `get_env` shall be allowed to be a coroutine. @minrk ?

**Comment by BerserkerTroll** [comment] 2018-10-24 14:01
BTW, this does not look like an issue report. I think questions should be asked somewhere else https://github.com/jupyterhub/kubespawner#getting-help
@consideRatio @willingc close as a non-issue?

**Comment by consideRatio** [comment] 2018-10-24 14:53
Woooo thanks for helping out and addressing @cmrfrd's question @BerserkerTroll!

I'm also customizing the environment variables for my users. I'm writing some custom logic in a `pre_spawn_start` function of a custom authenticator. It requires more overhead than @BerserkerTroll's example though. Something like this is what I do: https://github.com/consideRatio/z2jh-extended/blob/10fe7bbd4609224361a89fbbe6c6eefbc06db419/z2jh-extended/values.yaml#L14-L73

I'll close this @cmrfrd but feel free to contact us on Gitter or follow up here.

**Closed by consideRatio** 2018-10-24 14:53 UTC
