### ISSUE TITLE
Specify container command

### ISSUE THREAD

**Issue by minrk** [jupyterhub/kubespawner#31] opened 2017-03-14 14:28 UTC
Is it possible to specify the container command via config? To use the docker stacks, command must be set to `/usr/local/bin/singleuser.sh`, but I can't see how to do it here. In DockerSpawner, it's passed to `docker.create`

**Comment by yuvipanda** [comment] 2017-03-15 16:19
Ah, it currently just uses whatever is the 'cmd' in the Dockerfile. But yes, let's add a customization option too.

**Comment by yuvipanda** [comment] 2017-03-21 22:25
When I tried it with jupyter/pyspark-notebook, I get: 'error: Error response from daemon: Container command 'jupyterhub-singleuser' not found or does not exist.'

**Comment by yuvipanda** [comment] 2017-03-21 22:25
Because they need to be singleuser.sh. I'd rather have docker-stacks have jupyterhub-singleuser tho

**Comment by yuvipanda** [comment] 2017-03-21 22:28
Uh, no - jupyterhub-singleuser should also have just worked. Not sure why it didn't?

**Comment by yuvipanda** [comment] 2017-03-22 06:18
Not at all sure what's going on - but current suspicion is it's got something to do with the tini usage in the ENTRYPOINT for docker-stacks and how ENTRYPOINT and CMD interact.

**Comment by yuvipanda** [comment] 2017-03-24 02:34
Woah, if we set command explicitly for any container then spawning kernels breaks. WAAAT

**Comment by minrk** [comment] 2017-03-24 15:03
Same thing discovered in swarm mode: https://github.com/cassinyio/SwarmSpawner/issues/6

No idea what's up here, but may have to do with TTYs: https://github.com/docker/docker/issues/25644

**Comment by yuvipanda** [comment] 2017-03-24 18:55
docker inspect for non-working container:

```
$ docker inspect 535db8e663d7
[
    {
        "Id": "535db8e663d7912ebb970151a23a4b45fdb34e02fc330d3f3c55ee6aabd8167e",
        "Created": "2017-03-24T18:52:35.164316308Z",
        "Path": "/bin/sh",
        "Args": [
            "-c",
            "jupyterhub-singleuser   --port=8888   --ip=0.0.0.0   --user=\"$JPY_USER\"   --cookie-name=$JPY_COOKIE_NAME   --base-url=$JPY_BASE_URL   --hub-prefix=$JPY_HUB_PREFIX   --hub-api-url=$JPY_HUB_API_URL"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 16084,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2017-03-24T18:52:35.239216207Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:0ecf12ff9b800414281af0888b193fb4a98b6a938dcca966d387617e598d7721",
        "ResolvConfPath": "/mnt/sda1/var/lib/docker/containers/ff3e9509f336041850c52dac615980329ac713d39a0bc02d3ef4125aa99c151b/resolv.conf",
        "HostnamePath": "/mnt/sda1/var/lib/docker/containers/ff3e9509f336041850c52dac615980329ac713d39a0bc02d3ef4125aa99c151b/hostname",
        "HostsPath": "/var/lib/kubelet/pods/0ad9c420-10c3-11e7-a0ad-080027a0693f/etc-hosts",
        "LogPath": "/mnt/sda1/var/lib/docker/containers/535db8e663d7912ebb970151a23a4b45fdb34e02fc330d3f3c55ee6aabd8167e/535db8e663d7912ebb970151a23a4b45fdb34e02fc330d3f3c55ee6aabd8167e-json.log",
        "Name": "/k8s_notebook.a1895f9e_jupyter-l-1_default_0ad9c420-10c3-11e7-a0ad-080027a0693f_b1ac085d",
        "RestartCount": 0,
        "Driver": "overlay",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/var/lib/kubelet/pods/0ad9c420-10c3-11e7-a0ad-080027a0693f/volumes/kubernetes.io~empty-dir/no-api-access-please:/var/run/secrets/kubernetes.io/serviceaccount:ro",
                "/var/lib/kubelet/pods/0ad9c420-10c3-11e7-a0ad-080027a0693f/etc-hosts:/etc/hosts",
                "/var/lib/kubelet/pods/0ad9c420-10c3-11e7-a0ad-080027a0693f/containers/notebook/b1ac085d:/dev/termination-log"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "container:ff3e9509f336041850c52dac615980329ac713d39a0bc02d3ef4125aa99c151b",
            "PortBindings": null,
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": [
                "0"
            ],
            "IpcMode": "container:ff3e9509f336041850c52dac615980329ac713d39a0bc02d3ef4125aa99c151b",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 1000,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": [
                "seccomp=unconfined"
            ],
            "StorageOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 2,
            "Memory": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": -1,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "BlkioIOps": 0,
            "BlkioBps": 0,
            "SandboxSize": 0
        },
        "GraphDriver": {
            "Name": "overlay",
            "Data": {
                "LowerDir": "/mnt/sda1/var/lib/docker/overlay/7e5328a2c03cc81c7c04aa23bf4a47d252eb29f227fa0666aae9b5d1e3f0796b/root",
                "MergedDir": "/mnt/sda1/var/lib/docker/overlay/35db857f8474651a4eef8137f8ca3cafe2424808788f17b2baf9d98d5daffca6/merged",
                "UpperDir": "/mnt/sda1/var/lib/docker/overlay/35db857f8474651a4eef8137f8ca3cafe2424808788f17b2baf9d98d5daffca6/upper",
                "WorkDir": "/mnt/sda1/var/lib/docker/overlay/35db857f8474651a4eef8137f8ca3cafe2424808788f17b2baf9d98d5daffca6/work"
            }
        },
        "Mounts": [
            {
                "Source": "/var/lib/kubelet/pods/0ad9c420-10c3-11e7-a0ad-080027a0693f/volumes/kubernetes.io~empty-dir/no-api-access-please",
                "Destination": "/var/run/secrets/kubernetes.io/serviceaccount",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Source": "/var/lib/kubelet/pods/0ad9c420-10c3-11e7-a0ad-080027a0693f/etc-hosts",
                "Destination": "/etc/hosts",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Source": "/var/lib/kubelet/pods/0ad9c420-10c3-11e7-a0ad-080027a0693f/containers/notebook/b1ac085d",
                "Destination": "/dev/termination-log",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "jupyter-l-1",
            "Domainname": "",
            "User": "0",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8888/tcp": {}
            },
            "Tty": true,
            "OpenStdin": true,
            "StdinOnce": false,
            "Env": [
                "JPY_HUB_PREFIX=/hub/",
                "GIT_COMMITTER_NAME=l",
                "GIT_AUTHOR_NAME=l",
                "JPY_USER=l",
                "EMAIL=l@local",
                "JPY_BASE_URL=/user/l",
                "JUPYTERHUB_API_TOKEN=18a6b9d5672c45559bf5d79c70e52008",
                "JPY_COOKIE_NAME=jupyter-hub-token-l",
                "JPY_HUB_API_URL=http://10.0.0.58:8081/hub/api",
                "JPY_API_TOKEN=18a6b9d5672c45559bf5d79c70e52008",
                "PROXY_PUBLIC_PORT_80_TCP=tcp://10.0.0.14:80",
                "KUBERNETES_SERVICE_PORT_HTTPS=443",
                "KUBERNETES_PORT=tcp://10.0.0.1:443",
                "KUBERNETES_PORT_443_TCP_PORT=443",
                "HUB_PORT_8081_TCP_PROTO=tcp",
                "KUBERNETES_PORT_443_TCP_PROTO=tcp",
                "PROXY_PUBLIC_SERVICE_PORT=80",
                "PROXY_PUBLIC_PORT_80_TCP_PORT=80",
                "PROXY_API_SERVICE_PORT=8001",
                "PROXY_API_PORT=tcp://10.0.0.187:8001",
                "PROXY_API_PORT_8001_TCP_PORT=8001",
                "PROXY_API_SERVICE_HOST=10.0.0.187",
                "HUB_SERVICE_PORT=8081",
                "PROXY_API_PORT_8001_TCP_PROTO=tcp",
                "PROXY_PUBLIC_SERVICE_HOST=10.0.0.14",
                "HUB_PORT=tcp://10.0.0.58:8081",
                "HUB_PORT_8081_TCP_ADDR=10.0.0.58",
                "KUBERNETES_SERVICE_HOST=10.0.0.1",
                "KUBERNETES_SERVICE_PORT=443",
                "KUBERNETES_PORT_443_TCP_ADDR=10.0.0.1",
                "PROXY_PUBLIC_PORT_80_TCP_ADDR=10.0.0.14",
                "PROXY_API_PORT_8001_TCP=tcp://10.0.0.187:8001",
                "PROXY_API_PORT_8001_TCP_ADDR=10.0.0.187",
                "PROXY_PUBLIC_PORT=tcp://10.0.0.14:80",
                "PROXY_PUBLIC_PORT_80_TCP_PROTO=tcp",
                "HUB_SERVICE_HOST=10.0.0.58",
                "HUB_PORT_8081_TCP=tcp://10.0.0.58:8081",
                "HUB_PORT_8081_TCP_PORT=8081",
                "KUBERNETES_PORT_443_TCP=tcp://10.0.0.1:443",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "HOME=/home/jovyan",
                "USER=jovyan"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "jupyterhub-singleuser   --port=8888   --ip=0.0.0.0   --user=\"$JPY_USER\"   --cookie-name=$JPY_COOKIE_NAME   --base-url=$JPY_BASE_URL   --hub-prefix=$JPY_HUB_PREFIX   --hub-api-url=$JPY_HUB_API_URL"
            ],
            "Image": "yuvipanda/tiniest-notebook:v1.2",
            "Volumes": null,
            "WorkingDir": "/home/jovyan",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "io.kubernetes.container.hash": "a1895f9e",
                "io.kubernetes.container.name": "notebook",
                "io.kubernetes.container.ports": "[{\"containerPort\":8888,\"protocol\":\"TCP\"}]",
                "io.kubernetes.container.restartCount": "0",
                "io.kubernetes.container.terminationMessagePath": "/dev/termination-log",
                "io.kubernetes.pod.name": "jupyter-l-1",
                "io.kubernetes.pod.namespace": "default",
                "io.kubernetes.pod.terminationGracePeriod": "30",
                "io.kubernetes.pod.uid": "0ad9c420-10c3-11e7-a0ad-080027a0693f"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": null,
            "SandboxKey": "",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": null
        }
    }
]
```

**Comment by yuvipanda** [comment] 2017-03-24 18:57
For a non-working container:

```
[
    {
        "Id": "1edd7259722d4678b79b98aaba105f7c50c695f0549c477f32224653662f387b",
        "Created": "2017-03-24T18:56:48.177798108Z",
        "Path": "jupyterhub-singleuser",
        "Args": [
            "--user=\"ee\"",
            "--cookie-name=\"jupyter-hub-token-ee\"",
            "--base-url=\"/user/ee\"",
            "--hub-host=\"\"",
            "--hub-prefix=\"/hub/\"",
            "--hub-api-url=\"http://10.0.0.58:8081/hub/api\"",
            "--ip=\"0.0.0.0\"",
            "--port=8888"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 20403,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2017-03-24T18:56:48.250694309Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:0ecf12ff9b800414281af0888b193fb4a98b6a938dcca966d387617e598d7721",
        "ResolvConfPath": "/mnt/sda1/var/lib/docker/containers/8c46886934734347d0d2236c3cecb70cbde69cfca6e74c01848d15cca143ec5a/resolv.conf",
        "HostnamePath": "/mnt/sda1/var/lib/docker/containers/8c46886934734347d0d2236c3cecb70cbde69cfca6e74c01848d15cca143ec5a/hostname",
        "HostsPath": "/var/lib/kubelet/pods/a1b92093-10c3-11e7-a0ad-080027a0693f/etc-hosts",
        "LogPath": "/mnt/sda1/var/lib/docker/containers/1edd7259722d4678b79b98aaba105f7c50c695f0549c477f32224653662f387b/1edd7259722d4678b79b98aaba105f7c50c695f0549c477f32224653662f387b-json.log",
        "Name": "/k8s_notebook.8d2a9fa9_jupyter-ee-1_default_a1b92093-10c3-11e7-a0ad-080027a0693f_6114052a",
        "RestartCount": 0,
        "Driver": "overlay",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/var/lib/kubelet/pods/a1b92093-10c3-11e7-a0ad-080027a0693f/volumes/kubernetes.io~empty-dir/no-api-access-please:/var/run/secrets/kubernetes.io/serviceaccount:ro",
                "/var/lib/kubelet/pods/a1b92093-10c3-11e7-a0ad-080027a0693f/etc-hosts:/etc/hosts",
                "/var/lib/kubelet/pods/a1b92093-10c3-11e7-a0ad-080027a0693f/containers/notebook/6114052a:/dev/termination-log"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "container:8c46886934734347d0d2236c3cecb70cbde69cfca6e74c01848d15cca143ec5a",
            "PortBindings": null,
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": [
                "0"
            ],
            "IpcMode": "container:8c46886934734347d0d2236c3cecb70cbde69cfca6e74c01848d15cca143ec5a",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 1000,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": [
                "seccomp=unconfined"
            ],
            "StorageOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 2,
            "Memory": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": -1,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "BlkioIOps": 0,
            "BlkioBps": 0,
            "SandboxSize": 0
        },
        "GraphDriver": {
            "Name": "overlay",
            "Data": {
                "LowerDir": "/mnt/sda1/var/lib/docker/overlay/7e5328a2c03cc81c7c04aa23bf4a47d252eb29f227fa0666aae9b5d1e3f0796b/root",
                "MergedDir": "/mnt/sda1/var/lib/docker/overlay/b0e14133c566409893c7b6c4be63401998b2c0ed7ce4a65be1832f52b7fcf39c/merged",
                "UpperDir": "/mnt/sda1/var/lib/docker/overlay/b0e14133c566409893c7b6c4be63401998b2c0ed7ce4a65be1832f52b7fcf39c/upper",
                "WorkDir": "/mnt/sda1/var/lib/docker/overlay/b0e14133c566409893c7b6c4be63401998b2c0ed7ce4a65be1832f52b7fcf39c/work"
            }
        },
        "Mounts": [
            {
                "Source": "/var/lib/kubelet/pods/a1b92093-10c3-11e7-a0ad-080027a0693f/containers/notebook/6114052a",
                "Destination": "/dev/termination-log",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Source": "/var/lib/kubelet/pods/a1b92093-10c3-11e7-a0ad-080027a0693f/volumes/kubernetes.io~empty-dir/no-api-access-please",
                "Destination": "/var/run/secrets/kubernetes.io/serviceaccount",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Source": "/var/lib/kubelet/pods/a1b92093-10c3-11e7-a0ad-080027a0693f/etc-hosts",
                "Destination": "/etc/hosts",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "jupyter-ee-1",
            "Domainname": "",
            "User": "0",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8888/tcp": {}
            },
            "Tty": true,
            "OpenStdin": true,
            "StdinOnce": false,
            "Env": [
                "JPY_COOKIE_NAME=jupyter-hub-token-ee",
                "JUPYTERHUB_API_TOKEN=a439eb3e4b32433493f87665db2a47e5",
                "JPY_USER=ee",
                "JPY_BASE_URL=/user/ee",
                "EMAIL=ee@local",
                "JPY_API_TOKEN=a439eb3e4b32433493f87665db2a47e5",
                "GIT_AUTHOR_NAME=ee",
                "JPY_HUB_PREFIX=/hub/",
                "JPY_HUB_API_URL=http://10.0.0.58:8081/hub/api",
                "GIT_COMMITTER_NAME=ee",
                "HUB_SERVICE_PORT=8081",
                "PROXY_API_SERVICE_PORT=8001",
                "PROXY_API_PORT_8001_TCP_PORT=8001",
                "PROXY_PUBLIC_SERVICE_HOST=10.0.0.14",
                "PROXY_PUBLIC_SERVICE_PORT=80",
                "KUBERNETES_PORT_443_TCP_PORT=443",
                "HUB_PORT_8081_TCP_PORT=8081",
                "PROXY_PUBLIC_PORT=tcp://10.0.0.14:80",
                "HUB_PORT=tcp://10.0.0.58:8081",
                "KUBERNETES_SERVICE_HOST=10.0.0.1",
                "KUBERNETES_PORT_443_TCP=tcp://10.0.0.1:443",
                "PROXY_API_PORT_8001_TCP=tcp://10.0.0.187:8001",
                "PROXY_API_PORT_8001_TCP_PROTO=tcp",
                "PROXY_PUBLIC_PORT_80_TCP=tcp://10.0.0.14:80",
                "PROXY_PUBLIC_PORT_80_TCP_ADDR=10.0.0.14",
                "HUB_SERVICE_HOST=10.0.0.58",
                "PROXY_PUBLIC_PORT_80_TCP_PROTO=tcp",
                "HUB_PORT_8081_TCP=tcp://10.0.0.58:8081",
                "KUBERNETES_SERVICE_PORT_HTTPS=443",
                "KUBERNETES_PORT_443_TCP_PROTO=tcp",
                "KUBERNETES_PORT_443_TCP_ADDR=10.0.0.1",
                "PROXY_API_SERVICE_HOST=10.0.0.187",
                "KUBERNETES_SERVICE_PORT=443",
                "PROXY_API_PORT=tcp://10.0.0.187:8001",
                "PROXY_PUBLIC_PORT_80_TCP_PORT=80",
                "HUB_PORT_8081_TCP_PROTO=tcp",
                "HUB_PORT_8081_TCP_ADDR=10.0.0.58",
                "KUBERNETES_PORT=tcp://10.0.0.1:443",
                "PROXY_API_PORT_8001_TCP_ADDR=10.0.0.187",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "HOME=/home/jovyan",
                "USER=jovyan"
            ],
            "Cmd": null,
            "Image": "yuvipanda/tiniest-notebook:v1.2",
            "Volumes": null,
            "WorkingDir": "/home/jovyan",
            "Entrypoint": [
                "jupyterhub-singleuser",
                "--user=\"ee\"",
                "--cookie-name=\"jupyter-hub-token-ee\"",
                "--base-url=\"/user/ee\"",
                "--hub-host=\"\"",
                "--hub-prefix=\"/hub/\"",
                "--hub-api-url=\"http://10.0.0.58:8081/hub/api\"",
                "--ip=\"0.0.0.0\"",
                "--port=8888"
            ],
            "OnBuild": null,
            "Labels": {
                "io.kubernetes.container.hash": "8d2a9fa9",
                "io.kubernetes.container.name": "notebook",
                "io.kubernetes.container.ports": "[{\"containerPort\":8888,\"protocol\":\"TCP\"}]",
                "io.kubernetes.container.restartCount": "0",
                "io.kubernetes.container.terminationMessagePath": "/dev/termination-log",
                "io.kubernetes.pod.name": "jupyter-ee-1",
                "io.kubernetes.pod.namespace": "default",
                "io.kubernetes.pod.terminationGracePeriod": "30",
                "io.kubernetes.pod.uid": "a1b92093-10c3-11e7-a0ad-080027a0693f"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": null,
            "SandboxKey": "",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": null
        }
    }
]
```

Note that I've set tty and stdin on both of them - it seems to have no effect.

**Comment by yuvipanda** [comment] 2017-03-26 02:22
So I tried running:

```
FROM alpine:3.5

RUN apk add --no-cache python3 py-zmq strace
RUN pip3 install notebook

EXPOSE 8888

ENTRYPOINT ["jupyter", "notebook", "--no-browser", "--ip='0.0.0.0'"]
```

This fails! However,

```
FROM alpine:3.5

RUN apk add --no-cache python3 py-zmq strace
RUN pip3 install notebook

EXPOSE 8888

ENTRYPOINT ["strace", "-f", "-s1000", "jupyter", "notebook", "--no-browser", "--ip='0.0.0.0'"]
```

actually succeeds, so I'm increasingly convinced it's because it's pid 1 (or some underlying issue that is related to that)

**Comment by yuvipanda** [comment] 2017-03-26 02:37
A simpler reproduction case, when you are running on Linux:

```bash
sudo unshare --mount-proc -f -p ./bin/jupyter notebook
```

This has the exact same failure case. It makes the notebook start as pid 1.

**Comment by minrk** [comment] 2017-03-27 11:09
ipython/ipykernel#233 fixes a bug in the IPython kernel when its parent has PID 1. However, there is an issue here, that we want to set CMD *not* ENTRYPOINT. Helpfully, in Kubernetes command = ENTRYPOINT; args = CMD. I opened #38 to use `args` instead of `command`, which should also fix this (and be the right thing to do in general, I think).

**Comment by yuvipanda** [comment] 2017-03-28 18:18
Boo, now dockerstacks failing with:
```
	WarningFailed	Failed to start container with docker id 5c83e79d2589 with error: Error response from daemon: Container command 'tini' not found or does not exist.
```

but it seems to work locally.

**Comment by yuvipanda** [comment] 2017-03-28 21:36
And it's not that tini's path isn't fully specified.

```
  9s	9s	1	{kubelet gke-test-default-pool-ef3d2d3f-5js5}	spec.containers{notebook}	Warning	Failed	Failed to start container with docker id d7566d883071 with error: Error response from daemon: Container command '/usr/bin/local/tini' not found or does not exist.
```

After I modified the container image to set entrypoint to `/usr/bin/local/tini`

**Comment by yuvipanda** [comment] 2017-03-28 21:36
*facepalm*

**Comment by yuvipanda** [comment] 2017-03-28 21:40
When I fixed my typo, problem still persists:

```
  10s	10s	1	{kubelet gke-test-default-pool-ef3d2d3f-qdtz}	spec.containers{notebook}	Warning	Failed		Failed to start container with docker id 31380e4aa7a9 with error: Error response from daemon: Container command '/usr/bin/local/tini' not found or does not exist.
  1s	1s	1	{kubelet gke-test-default-pool-ef3d2d3f-qdtz}	spec.containers{notebook}	Warning	BackOff		Back-off restarting failed docker container
```

So this isn't a PATH issue. I'm not sure what's going on, tbh.

**Comment by minrk** [comment] 2017-03-29 12:26
`/usr/bin/local/tini` should be `/usr/local/bin/tini`. But if it's not on PATH, something's messed up in the env, right?

**Comment by yuvipanda** [comment] 2017-04-26 19:46
So last on this is that docker-stacks works if you don't have persistent storage, but doesn't work if you do. Am mystified, but it's probably because docker-stacks puts something in $HOME that is absolutely required for it to function, and persistent storage just mounts persistent storage in $HOME. 

At least for the default helm chart, I definitely want the persistent storage to be in $HOME rather than $HOME/work, so someone needs to dig into docker-stacks to figure out why this is happening and fix it. Since the docker-stacks are pretty massive as well, I'm mostly focusing on getting s2i to allow dynamic building of equivalent custom stacks now instead.

**Comment by danielfrg** [comment] 2017-04-27 15:53
I can confirm that this works with the latest `docker-stacks` images I have extended the `r-notebook` to test the rstudio proxy and that worked with this jupyterhub settings:

```python
c.KubeSpawner.cmd = ["/usr/local/bin/start-singleuser.sh", "--allow-root"]
c.KubeSpawner.singleuser_image_spec = 'danielfrg/nbrsessionproxy:0.2.0'
```

**Comment by minrk** [comment] 2017-05-02 11:28
@yuvipanda do you get any errors back? Could it be that WORKDIR is $HOME/work and you need to change that if you are deleting that directory by mounting a volume?

**Comment by yuvipanda** [comment] 2017-05-19 23:22
Going to close this now since we've a tracking ticket on docker-stacks

**Closed by yuvipanda** 2017-05-19 23:22 UTC
